### ISSUE TITLE
nav: click removes highlight

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/gatsby-theme-iterative#135]
See anything strange in this image?

<img width="833" alt="image" src="https://user-images.githubusercontent.com/1477535/168699657-35e76b08-451e-435b-b98c-a0fb13691bc6.png">

> https://dvc.org/doc/use-cases/ci-cd-for-machine-learning

I clicked the nav entry of the page after it loaded and it stopped being bold. Should look like this:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/1477535/168699724-e2806944-7d51-4ff3-965e-a9ae0c460dd2.png">

**Comment by yathomasi** [comment]
@jorgeorpinel
I couldn't replicate it. Is this still an issue?

**Comment by jorgeorpinel** [comment]
Yep

https://user-images.githubusercontent.com/1477535/204681559-1a21aef4-b9e6-4465-ad12-176e465dda33.mov

**Comment by yathomasi** [comment]
Closing this as fixed. 

https://user-images.githubusercontent.com/20840228/207810805-fa0e0871-b1b5-416d-8927-9eb901c69ad5.mov
