### ISSUE TITLE
Improve Tab component styling and support nesting

### ISSUE THREAD

**Issue by julieg18** [iterative/gatsby-theme-iterative#138]
> (minor) maybe a thin left border rather than shading - similar to but more subtle than quotes - would be better

[comment](https://github.com/iterative/cml.dev/pull/136#issuecomment-953910206) by @casperdcl 

> Agreed on border over over shading, or maybe even both- border having high contrast to serve as an obvious indicator and subtle shading to make it a little easier to track across the whole box without making every tab box an eye-catching callout.

[comment](https://github.com/iterative/cml.dev/pull/136#issuecomment-954055816) by @rogermparent

**Comment by rogermparent** [comment]
Linking https://github.com/iterative/dvc.org/pull/4123#pullrequestreview-1189056725 and reviving this is a more general issue

**Comment by rogermparent** [comment]
Funny enough, https://github.com/iterative/dvc.org/pull/4118 which was merged today happened to fix the example case of nested tabs!

I do think keeping the code blocks from going on that long is ideal when possible, even if the alternative isn't broken.
