### ISSUE TITLE
Review and Clear Websites' Dependabot alerts

### ISSUE THREAD

**Issue by julieg18** [iterative/gatsby-theme-iterative#44]
Currently all of our websites are receiving security alerts. I've looked over them and didn't spot anything we need to worry about, but we should do more research to be sure. We could upgrade packages, fixing the ones we want to clear, and dismiss the rest. 

cc @iterative/websites

**Comment by rogermparent** [comment]
Technically this is a never-ending battle, but we temporarily cleared all website repos' built up Dependabot alerts and now we're just keeping up with maintenance!
