### ISSUE TITLE
Browser back should be taking to the same place on the page

### ISSUE THREAD

**Issue by shcheklein** [iterative/gatsby-theme-iterative#64]
Browser by default saves state of the page (I think scroll position?). Check gatsby docs, try to scroll down, navigate and get back. It's broken in our case:

https://user-images.githubusercontent.com/3659196/187054896-8e6d506a-057c-466f-b079-4766d3f92227.mov

**Comment by rogermparent** [comment]
This looks fixed and closable on my machine! Likely was since #33 though new changes may have made it cleaner.

https://user-images.githubusercontent.com/9111807/236011439-5109659f-2b5a-4586-b75c-2540e03721b6.mp4
